language: d

services:
  - docker

d:
  - dmd
  - dmd-beta
  - dmd-nightly

matrix:
  allow_failures:
    - d: dmd-nightly
  include:
    - d: ldc-1.23.0
      env: TOUR_DEPLOY=1

branches:
  only:
    - master
    - testing

addons:
  apt:
    packages:
    - libevent-dev
    - libblas-dev
    - liblapack-dev
    - libopenblas-dev

script:
  - ./ci/travis.sh

after_success:
  - ./ci/deploy.sh
